LanguageChat/Models/TranslateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LanguageChat.Models
{
    public class TranslateViewModel
    {
        public int Id { get; set; }
        public string textToTranslate { get; set; }
        public string translatedText { get; set; }
        public string fromLang { get; set; }
        public string toLang { get; set; }
        public List<Language> LanguageList { get; set; }

    }
}

LanguageChat/Controllers/TranslateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Http;
using LanguageChat.Models;
using System.Text;

namespace LanguageChat.Controllers
{
    public class TranslateController : Controller
    {
        WebClient webClient = new WebClient();
        private ApplicationDbContext _dbContext = new ApplicationDbContext();
        // GET: Translate
        public ActionResult Index()
        {
            var getLanguages = _dbContext.Languages.ToList();
            TranslateViewModel translateViwModel = new TranslateViewModel();
            translateViwModel.LanguageList = getLanguages;
            return PartialView("Index", translateViwModel);
        }

        [HttpPost]
        public ActionResult Index(TranslateViewModel model)
        {
            var getLanguages = _dbContext.Languages.ToList();
            int cnvrtFrom = Convert.ToInt32(model.fromLang);
            int cnvrtTo = Convert.ToInt32(model.toLang);
            var from = _dbContext.Languages.Where(x => x.Id == cnvrtFrom).FirstOrDefault();
            var to = _dbContext.Languages.Where(x => x.Id == cnvrtTo).FirstOrDefault();
            string langPair = from.Value.ToLower() + "|" + to.Value.ToLower();
            string text = model.textToTranslate;
            string url = String.Format(@"http://translatewebapi.azurewebsites.net/api/Translate?text={0}&langs={1}",text,langPair);
            string result;
            using (WebClient webClient = new WebClient())
            {
                webClient.Encoding = Encoding.UTF8;
                 result = webClient.DownloadString(url);
            }
            TranslateViewModel translateViwModel = new TranslateViewModel();
            translateViwModel.fromLang = model.fromLang;
            translateViwModel.toLang = model.toLang;
            translateViwModel.textToTranslate = model.textToTranslate;
            translateViwModel.translatedText = result;
            translateViwModel.LanguageList = getLanguages;


            return PartialView("Translated", translateViwModel);
        }
    }
}

LanguageChat/Views/Translate/Index.cshtml
@model LanguageChat.Models.TranslateViewModel
<div class="row form-inline translator">
    @using (Ajax.BeginForm("Index", "Translate", new AjaxOptions() { UpdateTargetId = "update", HttpMethod = "POST" }))
    {

        @Html.TextBoxFor(m => m.textToTranslate, new { @class = "translateTxtBox", placeholder = "Text To Translate" })
        @Html.DropDownListFor(m => m.fromLang, new SelectList(Model.LanguageList, "Id", "Name"), "Translate From", new { @class = "translateDropDown", id = "langFrom" })
        <button type="button" class="btn btn-sm btn-success switchLang" id="switchLang">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            <i class="fa fa-arrow-right" aria-hidden="true"></i>
        </button>
        @Html.DropDownListFor(m => m.toLang, new SelectList(Model.LanguageList, "Id", "Name"), "Translate To", new { @class = "translateDropDown", id = "langTo" })
        <span id="update"></span>
       
        <input type="submit" class="btn btn-sm btn-success switchLang" value="Translate" />

    }
    
</div>

<script>

    $('#switchLang').click(function () {
        var from = $('#langFrom').val();
        var fromName = $('#langFrom  :selected').text();
        var to = $('#langTo').val();
        var toName = $('#langTo  :selected').text();

        $('#langFrom').val(to);
        $('#langFrom  :selected').text(toName);

        $('#langTo').val(from);
        $('#langTo  :selected').text(fromName);
    });
</script>

LanguageChat/Views/Translate/Translated.cshtml
@model LanguageChat.Models.TranslateViewModel
@Html.TextBoxFor(m => m.translatedText, new { @class = "translateTxtBox", @Value = Model.translatedText })