LanguageChat/Controllers/ChatController.cs
using LanguageChat.Hubs;
using LanguageChat.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Hubs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LanguageChat.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index(string id)
        {
            if(id !=null)
            {
                ViewBag.AddUserId = id;
            }

            return View();
        }
    }

}

LanguageChat/Controllers/FriendController.cs
using LanguageChat.Models;
using LanguageChat.Models.Chat;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LanguageChat.Controllers
{
    public class FriendController : Controller
    {
        private ApplicationDbContext _dbContext = new ApplicationDbContext();
        // GET: Friend

       public ActionResult FriendsList()
         {
            var userId = User.Identity.GetUserId();       
            List<FriendList> myFriends = _dbContext.FriendLists.Where(x=>x.FriendOne == userId || x.FriendSecond==userId).Where(y=>y.FriendRequestOne==true &&y.FriendRequestSecond==true).ToList();
            List<string> friendsId = new List<string>();
            foreach (var item in myFriends)
            {
                if (item.FriendOne == userId)
                {
                    friendsId.Add(item.FriendSecond);
                }
                else
                    friendsId.Add(item.FriendOne);
            }
            var friendsDetails = _dbContext.Users.Where(x => friendsId.Any(y => y == x.Id)).ToList();
          return PartialView(friendsDetails);
         }

        public ActionResult RequestFriend()
        {
            var userId = User.Identity.GetUserId();
            List<string> friendsId = new List<string>();
            var requestFriends = _dbContext.FriendLists.Where(x => x.FriendOne == userId || x.FriendSecond == userId);
            var notConfirmedFriend = requestFriends.Where(x => x.FriendRequestOne == false || x.FriendRequestSecond == false);

            foreach (var item in notConfirmedFriend)
            {
                if (item.FriendSecond == userId)
                {
                    friendsId.Add(item.FriendOne);
                }
            }
            var friendsDetails = _dbContext.Users.Where(x => friendsId.Any(y => y == x.Id)).ToList();
            return PartialView(friendsDetails);
        }

        public ActionResult ConfirmFriendRequest(string id)
        {
            var userId = User.Identity.GetUserId();
            var toConfirm = _dbContext.FriendLists.Where(x=>(x.FriendOne == userId && x.FriendSecond == id) || (x.FriendOne==id && x.FriendSecond==userId)).Where(y=>y.FriendRequestOne==false || y.FriendRequestSecond==false).FirstOrDefault();

            if (toConfirm.FriendOne == userId)
            {
                toConfirm.FriendRequestOne = true;
            }
            else
                toConfirm.FriendRequestSecond = true;


            _dbContext.Entry(toConfirm).State = EntityState.Modified;
            _dbContext.SaveChanges();
            return RedirectToAction("FriendsList");
        }

        public ActionResult NonConfirmFriendRequest(string id)
        {
            var userId = User.Identity.GetUserId();
            var toConfirm = _dbContext.FriendLists.Where(x => (x.FriendOne == userId && x.FriendSecond == id) || (x.FriendOne == id && x.FriendSecond == userId)).Where(y => y.FriendRequestOne == false || y.FriendRequestSecond == false).FirstOrDefault();

            _dbContext.FriendLists.Remove(toConfirm);
            _dbContext.SaveChanges();
            return RedirectToAction("FriendsList");
        }

        public ActionResult DeleteFriend(string id)
        {
            var userId = User.Identity.GetUserId();
            var toConfirm = _dbContext.FriendLists.Where(x => (x.FriendOne == userId && x.FriendSecond == id) || (x.FriendOne == id && x.FriendSecond == userId)).FirstOrDefault();

            _dbContext.FriendLists.Remove(toConfirm);
            _dbContext.SaveChanges();
            return RedirectToAction("FriendsList");
        }

        public ActionResult Index(string id)
        {
            string fromUserId = User.Identity.GetUserId();
            var friendList = _dbContext.FriendLists.Where(x => (x.FriendOne == fromUserId && x.FriendSecond == id)|| (x.FriendOne==id && x.FriendSecond==fromUserId)).ToList();
            if(friendList.Count == 0)
            {
                AddFriend(id);
            }
            return RedirectToAction("UserProfile", "Settings",new {id = id });
        }

        public void AddFriend(string id)
        {
            string userid = User.Identity.GetUserId();

            FriendList newFriend = new FriendList
            {
                FriendOne = userid,
                FriendSecond = id,
                FriendRequestOne = true,
                FriendRequestSecond = false,
                RequestDate = DateTime.Now
            };
            _dbContext.FriendLists.Add(newFriend);
            _dbContext.SaveChanges();
        }
    }
}

LanguageChat/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using LanguageChat.Models;

namespace LanguageChat.Controllers
{
    public class SearchController : Controller
    {
        private ApplicationDbContext _dbContext;

        public SearchController()
        {
            _dbContext = new ApplicationDbContext(); 
        }

        // GET: Search
        public ActionResult UserSearch()
        {
            var getLanguages = _dbContext.Languages.ToList();
            UserSearchModel model = new UserSearchModel();
            model.LanguageList = getLanguages;
            var viewModel = new UserSearchModel { LanguageList = getLanguages };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult UserSearch(UserSearchModel searchModel)
        {
            var res = userSearchModel(searchModel).ToList();

            return PartialView("SearchResult",res);
        }


        public List<UserDetail> userSearchModel(UserSearchModel searchModel)
        {
            string userid = User.Identity.GetUserId();
            var user = _dbContext.UserDetails.Where(x => x.Id == userid);
            var result = _dbContext.UserDetails.Except(user).ToList().AsQueryable();
            List<Connection> usersFound = new List<Connection>();         
            if (searchModel != null)
            {

                if (!String.IsNullOrEmpty(searchModel.Id))
                    result = result.Where(x => x.Id == searchModel.Id);
                if (searchModel.Male && searchModel.Female)
                {
                    result = result.Where(x => x.Sex == "Male" || x.Sex == "Female");
                }else
                if (searchModel.Male)
                {
                    result = result.Where(x => x.Sex == "Male");
                }else
                if (searchModel.Female)
                {
                    result = result.Where(x => x.Sex == "Female");
                }
          
                if (searchModel.AgeFrom.HasValue)
                    result = result.Where(x => DateTime.Now.Year - x.Birthday.Year >= searchModel.AgeFrom);
                if (searchModel.AgeTo.HasValue)
                    result = result.Where(x => DateTime.Now.Year - x.Birthday.Year <= searchModel.AgeTo);

                if (!searchModel.LanguageId.All(item => item == 0))
                {
                    List<UserDetailLanguage> usrDetails = new List<UserDetailLanguage>();
                    foreach (var item in searchModel.LanguageId)
                    {
                        var details = _dbContext.UserDetailLanguages.Where(x => x.LanguageId == item).ToList();
                        foreach (var item2 in details)
                        {
                            usrDetails.Add(item2);
                        }
                    }
                    result = result.Where(x => usrDetails.Intersect(x.UserDetailLanguages).Count() > 0);
                }

            }
            
            return result.ToList();
        }
    }
}

LanguageChat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-social.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-formhelpers.min.css" rel="stylesheet" />
    @*<link href="~/Content/custom.css" rel="stylesheet" />*@
    <link href="~/Content/bootstrap-multiselect.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" Language Chat!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand fa fa-commenting-o fa-lg" })
            </div>

            <div class="navbar-collapse collapse">

                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-cogs"></i> User Settings <span class="fa fa-chevron-down"></span></a>
                            <ul class="menuDrop dropdown-menu">
                                <li><a href="@Url.Action("UserInformation", "Settings")"><i class="fa fa-info"></i> User Information</a></li>
                                <li><a href="@Url.Action("Languages", "Settings")"><i class="fa fa-language"></i> Languages</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("UserSearch", "Search")"><i class="fa fa-search"></i> Search</a></li>
                        <li><a href="@Url.Action("Index", "Chat")"><i class="fa fa-envelope-o"></i> Messages</a></li>
                        <li><a href="@Url.Action("FriendsList", "Friend")"><i class="fa fa-users"></i> Friends</a></li>
                    </ul>
                } 

                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>
    <div class="bodyContainer">
        <div class="">
                @RenderBody()      
        </div>
    </div>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.1.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/chatboxManager.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            $('.dropdown-toggle').dropdown();
        });
    </script>
</body>
</html>
<style>
    ul.menuDrop{
        background-color:black;     
    }
   .menuDrop li a{
        color:#FFFFFF;
    }
</style>