LanguageChat/Controllers/ChatController.cs
using LanguageChat.Hubs;
using LanguageChat.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Hubs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LanguageChat.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index(string id)
        {
            if(id !=null)
            {
                ViewBag.AddUserId = id;
            }

            return View();
        }
    }

}

LanguageChat/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using LanguageChat.Models;

namespace LanguageChat.Controllers
{
    public class SearchController : Controller
    {
        private ApplicationDbContext _dbContext;

        public SearchController()
        {
            _dbContext = new ApplicationDbContext(); 
        }

        // GET: Search
        public ActionResult UserSearch()
        {
            var getLanguages = _dbContext.Languages.ToList();
            UserSearchModel model = new UserSearchModel();
            model.LanguageList = getLanguages;
            var viewModel = new UserSearchModel { LanguageList = getLanguages };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult UserSearch(UserSearchModel searchModel)
        {
            var res = userSearchModel(searchModel).ToList();

            return PartialView("SearchResult",res);
        }


        public List<UserDetail> userSearchModel(UserSearchModel searchModel)
        {
            string userid = User.Identity.GetUserId();
            var user = _dbContext.UserDetails.Where(x => x.Id == userid);
            var result = _dbContext.UserDetails.Except(user).ToList().AsQueryable();
            List<Connection> usersFound = new List<Connection>();         
            if (searchModel != null)
            {

                if (!String.IsNullOrEmpty(searchModel.Id))
                    result = result.Where(x => x.Id == searchModel.Id);
                if (searchModel.Male && searchModel.Female)
                {
                    result = result.Where(x => x.Sex == "Male" || x.Sex == "Female");
                }else
                if (searchModel.Male)
                {
                    result = result.Where(x => x.Sex == "Male");
                }else
                if (searchModel.Female)
                {
                    result = result.Where(x => x.Sex == "Female");
                }
          
                if (searchModel.AgeFrom.HasValue)
                    result = result.Where(x => DateTime.Now.Year - x.Birthday.Year >= searchModel.AgeFrom);
                if (searchModel.AgeTo.HasValue)
                    result = result.Where(x => DateTime.Now.Year - x.Birthday.Year <= searchModel.AgeTo);

                if (!searchModel.LanguageId.All(item => item == 0))
                {
                    List<UserDetailLanguage> usrDetails = new List<UserDetailLanguage>();
                    foreach (var item in searchModel.LanguageId)
                    {
                        var details = _dbContext.UserDetailLanguages.Where(x => x.LanguageId == item).ToList();
                        foreach (var item2 in details)
                        {
                            usrDetails.Add(item2);
                        }
                    }
                    result = result.Where(x => usrDetails.Intersect(x.UserDetailLanguages).Count() > 0);
                }

            }
            
            return result.ToList();
        }
    }
}

LanguageChat/Controllers/SettingsController.cs
using LanguageChat.Models;
using LanguageChat.Models.Chat;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static LanguageChat.Models.Connection;

namespace LanguageChat.Controllers
{
    public class SettingsController : Controller
    {
        private ApplicationDbContext _dbContext = new ApplicationDbContext();
        // GET: Settings
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserProfile(string id)
        {
            var userInfos = _dbContext.UserDetails.Where(x => x.Id == id).ToList().FirstOrDefault();
            
            return PartialView(userInfos);
        }


        public ActionResult UserInformation()
        {
            string userid = User.Identity.GetUserId();

            UserDetail userDetail = _dbContext.UserDetails.Where(x => x.Id == userid).FirstOrDefault();
            if(userDetail ==null)
            {
                userDetail = new UserDetail();
                userDetail.Country = "US";
            }
            return PartialView(userDetail);
        }
        [HttpPost]
        public ActionResult UserInformation(UserDetail details)
        {

            if (ModelState.IsValid)
            {
                string userid = User.Identity.GetUserId();
                UserDetail userDetail = _dbContext.UserDetails.Where(x => x.Id == userid).FirstOrDefault();
                byte[] imageData = null;
                if(Request.Files.Count >0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["UserPhoto"];

                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        imageData = binary.ReadBytes(poImgFile.ContentLength);
                    }
                    var user = _dbContext.Users.Where(x => x.Id == userid).SingleOrDefault();
                    user.UserPhoto = imageData;
                }


                if(userDetail == null)
                {
                    UserDetail newUserDetail = new UserDetail();
                    newUserDetail.Id= userid;
                    newUserDetail.Sex = details.Sex;
                    newUserDetail.Birthday = details.Birthday;
                    newUserDetail.Country = details.Country;
                    newUserDetail.About = details.About;
                    _dbContext.UserDetails.Add(newUserDetail);

                }
                else
                {
                    userDetail.Sex = details.Sex;
                    userDetail.Birthday = details.Birthday;
                    userDetail.Country = details.Country;
                    userDetail.About = details.About;

                    _dbContext.Entry(userDetail).State = EntityState.Modified;
                }
                _dbContext.SaveChanges();
                return RedirectToAction("UserInformation");
            }
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            return PartialView(details);
        }


        public ActionResult Languages()
        {
            var getLanguages = _dbContext.Languages.ToList();
            var languages = new LanguageViewModel { LanguageList = getLanguages };
            return View("Languages", languages);
        }

        [HttpPost]
        public ActionResult KnownLanguages(LanguageViewModel languageList)
        {
            int languageId = languageList.LanguageId;
            Language lang = _dbContext.Languages.Where(x => x.Id == languageId).FirstOrDefault();
            if (ModelState.IsValid)
            {              
                string userid = User.Identity.GetUserId();

                UserDetailLanguage userDetailLanguage = new UserDetailLanguage();
                userDetailLanguage.UserDetailId = userid;
                userDetailLanguage.LanguageId = languageId;
                userDetailLanguage.IsKnown = true;

                var ifExist = _dbContext.UserDetailLanguages.Where(x => x.LanguageId == userDetailLanguage.LanguageId).Where(x => x.UserDetailId == userDetailLanguage.UserDetailId).Where(x => x.IsKnown == userDetailLanguage.IsKnown).FirstOrDefault();
                if (ifExist !=null)
                {
                    return RedirectToAction("Languages");
                }
                else
                {
                    _dbContext.UserDetailLanguages.Add(userDetailLanguage);
                    _dbContext.SaveChanges();
                }
            }

            var knownLanguages = _dbContext.UserDetailLanguages.Where(c => c.IsKnown).Select(c => c.Language);
            return RedirectToAction("Languages");
        }

        [HttpPost]
        public ActionResult UnknownLanguages(LanguageViewModel languageList)
        {
            int languageId = languageList.LanguageId;
            Language lang = _dbContext.Languages.Where(x => x.Id == languageId).FirstOrDefault();
            if (ModelState.IsValid)
            {
                string userid = User.Identity.GetUserId();

                UserDetailLanguage userDetailLanguage = new UserDetailLanguage();
                userDetailLanguage.UserDetailId = userid;
                userDetailLanguage.LanguageId = languageId;
                userDetailLanguage.IsKnown = false;

                var ifExist = _dbContext.UserDetailLanguages.Where(x => x.LanguageId == userDetailLanguage.LanguageId).Where(x => x.UserDetailId == userDetailLanguage.UserDetailId).Where(x =>x.IsKnown == userDetailLanguage.IsKnown).FirstOrDefault();
                if(ifExist != null)
                {
                    return RedirectToAction("Languages");
                }
                else
                {
                    _dbContext.UserDetailLanguages.Add(userDetailLanguage);
                    _dbContext.SaveChanges();
                }
            }

            var knownLanguages = _dbContext.UserDetailLanguages.Where(c => c.IsKnown).Select(c => c.Language);
            return RedirectToAction("Languages");
        }

        public ActionResult ListKnownLanguages()
        {
            string userid = User.Identity.GetUserId();
            var knownLanguages = _dbContext.UserDetailLanguages.Where(c => c.UserDetailId ==userid).Where(c => c.IsKnown).Select(c => c.Language);

            return PartialView(knownLanguages);
        }

        public ActionResult ListUnknownLanguages()
        {
            string userid = User.Identity.GetUserId();
            var unKnownLanguages = _dbContext.UserDetailLanguages.Where(c => c.UserDetailId == userid).Where(c => !c.IsKnown).Select(c => c.Language);

            return PartialView(unKnownLanguages);
        }

        public ActionResult Delete(int id)
        {
            string userid = User.Identity.GetUserId();

            var toDelete = _dbContext.UserDetailLanguages.Where(x => x.LanguageId == id).Where(x => x.UserDetailId == userid).FirstOrDefault();
            _dbContext.UserDetailLanguages.Remove(toDelete);
            _dbContext.SaveChanges();
            return RedirectToAction("Languages");
        }

        public FileContentResult UserPhotos(string id)
        {
            var userHavePhoto = _dbContext.Users.Where(x => x.Id == id).FirstOrDefault();
            string noPhoto = HttpContext.Server.MapPath(@"/Content/Images/avatar.jpg");

            if (userHavePhoto.UserPhoto == null)
            {
                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(noPhoto);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(noPhoto, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);
                return File(imageData, "image/jpg");
            }

            return new FileContentResult(userHavePhoto.UserPhoto, "image/jpeg");

        }



    }
}

LanguageChat/Views/Search/SearchResult.cshtml
@model IEnumerable<LanguageChat.Models.UserDetail>


@foreach (var item in Model)
{
    <div class="row searchRow">
        <div class="col-sm-2 searchAvatar">
            <img src="@Url.Action("UserPhotos", "Settings", new {id = item.Id })" width="100" height="100" class="imgC" />
        </div>

        <div class="col-sm-3 searchCol">
            <p style="font-size:11px"><b>Email: </b> @Html.DisplayFor(modelItem => item.User.Email) </p>
            <p style="font-size:11px"><b>Age: </b> @item.Age</p>
            <p style="font-size:11px"><b>Gender: </b> @Html.DisplayFor(modelItem => item.Sex) </p>
            <p style="font-size:11px"><b>Country: </b><span class="bfh-countries" data-country="@item.Country"></span></p>
        </div>

        <div class="col-sm-3 searchCol">
            <p style="font-size:14px"><b>About me :</b> @Html.DisplayFor(modelItem => item.About) </p>
        </div>

        <div class="col-sm-1 searchColButton">
            <div class="btn-group">
                <a class="resultItem btn btn-lg btn-primary" href="@Url.Action("Index", "Chat" , new {id= item.Id})" aria-label="Go to chat" id="@item.Id">
                    <i class="fa fa-commenting-o" aria-hidden="true"></i>
                </a>
                <a class="btn btn-lg btn-primary" href="@Url.Action("UserProfile", "Settings" , new { id=item.Id })" aria-label="Go to user profile">
                    <i class="fa fa-users" aria-hidden="true"></i>
                </a>
            </div>       
        </div>
    </div>
    <br/>
}
<script src="~/Scripts/bootstrap-formhelpers.min.js"></script>
<script>

    $('.resultItem').click(function () {
       var ids = this.id;
       addNewPersonToList(ids)       
    });

    function addNewPersonToList(id) {
        console.log("id: " + id);
        var chatHub = $.connection.chatHub;
            chatHub.server.addNewUserMessage(id);
    }

</script>
<style>
    .searchRow{
        background:rgba(74, 101, 126,1);
        display: table; 
        margin-bottom:2px;
        border-radius:5px;
         
    }
    .searchCol > p {
        color:white;
    }
    .searchColButton{
     border-left: 1px solid;
     text-align:center;
     display: table-cell;
     float: none;
     vertical-align: middle;
     padding-left: 10px;
    }

    .searchCol{
     display: table-cell;
     padding-top:10px;
    text-align: left;
    }

    .searchAvatar{
     white-space: nowrap;   
    text-align: center; margin: 1em 0;
    padding-left: 10px;
    }

    .imgC{
         vertical-align: middle;
    }

    .helper {
    display: inline-block;
    height: 100%;
    vertical-align: middle;
}
</style>

LanguageChat/Views/Search/UserSearch.cshtml
@model LanguageChat.Models.UserSearchModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "UserSearch";
}
<div class="searchMainTheme">
    <div class="col-sm-2 settings" style="; text-align:center;">
        @using (Ajax.BeginForm("UserSearch", "Search", new AjaxOptions() { UpdateTargetId = "result", HttpMethod = "POST" }))
        {
            @Html.AntiForgeryToken()           
                <h3>Search Settings</h3>
                <div class="form-group form-inline row center-block">
                    @Html.Label("Gender: ")
                    @Html.LabelFor(x => x.Male)
                    @Html.CheckBoxFor(x => x.Male)
                    @Html.LabelFor(x => x.Female)
                    @Html.CheckBoxFor(x => x.Female)
                </div>

                <div class="form-group form-inline row center-block">
                    @Html.Label("Age: ")
                    @Html.DropDownListFor(m => m.AgeFrom, Enumerable.Range(0, 110).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
                    @Html.Label(" - ")
                    @Html.DropDownListFor(m => m.AgeTo, Enumerable.Range(0, 110).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
                </div>

                <div class="form-group form-inline row center-block" id="languages">
                    @Html.Label("Add language(s) ")
                    @Html.DropDownListFor(m => m.LanguageId, new SelectList(Model.LanguageList, "Id", "Name"), new { multiple = "multiple", id = "dropUp" })
                </div>

                <div class="form-group form-inline">
                    <button type="submit" class="btn btn-success btn-block">
                        <i class="fa fa-search" aria-hidden="true"></i> Search
                    </button>
                </div>
         
        }
    </div>

    <div id="result" class="col-sm-9 result">
    </div>

</div>

<style>
    .searchSettings{
              text-align: center;
              margin: 20px 0;
    }

    .settings{
        /*margin-top: 5%;*/
        padding-top:5%;
        background-color:#4a657e;  
        color:white;
        height:100vh;
    }
    .result{
        margin-top:5%;
        margin-left:10px;
      
    }
    .searchMainTheme{
        background-color:#82AED9;        
        height:100vh;
    }


}
    }

</style>

<script type="text/javascript">
    $(document).ready(function() {
        $('#dropUp').val(['1']).multiselect({
            enableFiltering: true,
            includeSelectAllOption: true,
            maxHeight: 400,
            allSelectedText: 'Select all'
        });
    });
</script>